# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_dbt_project'
version: '1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'my_dbt_profile' # Make sure this matches the name in profiles.yml

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]       # Directories to where your model and source files live
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]       
macro-paths: ["macros"] 
snapshot-paths: ["snapshots"]

target-path: 'target' # directory which will store compiled SQL files

clean-targets:        # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  my_dbt_project:
    bronze:
      +schema: bronze
      +materialized: 'table'  # Configured to create tables in the bronze schema
    silver:
      +schema: silver
      +materialized: 'table'  # Configured to create tables in the silver schema
    gold:
      +schema: gold
      +materialized: 'table'  # Configured to create tables in the gold schema